package com.example.courseschedule.dto;

import lombok.Data;

@Data
public class MyCourseDTO {
    private Long selectionId;
    private Long teachingClassId;
    private String courseName;
    private String teacherName;
    private Double credits;

    public MyCourseDTO(Long selectionId, Long teachingClassId, String courseName, String teacherName, Double credits) {
        this.selectionId = selectionId;
        this.teachingClassId = teachingClassId;
        this.courseName = courseName;
        this.teacherName = teacherName;
        this.credits = credits;
    }

    // Getters and setters are generated by @Data
} 