package com.example.courseschedule.dto;

import lombok.Data;

@Data
public class MyCourseDTO {
    private Long courseId;
    private String courseName;
    private Double credits;
    private String teacherName;
    private String classCode;
    private String selectionTime;

    public MyCourseDTO(Long courseId, String courseName, Double credits, String teacherName, String classCode, String selectionTime) {
        this.courseId = courseId;
        this.courseName = courseName;
        this.credits = credits;
        this.teacherName = teacherName;
        this.classCode = classCode;
        this.selectionTime = selectionTime;
    }

    // Getters and setters are generated by @Data
} 