@startuml 教师按周查看课表流程图
title 教师按周查看课表流程图

start

:教师访问课表页面;
:身份验证;

if (身份验证通过?) then (是)
    :查询教师的教学班;
    :查询指定周的课表安排;
    :查询上课教室信息;
    :组装课表数据;
    :显示当前周课表;
    
    while (需要查看其他操作?) is (是)
        if (切换周次?) then (是)
            :选择其他周次;
            :查询指定周课表;
            :显示指定周课表;
        elseif (查看课程详情?) then (是)
            :点击某节课;
            :查询课程详细信息;
            
            if (课程存在且有权限?) then (是)
                :查询选课学生列表;
                :组装课程详细信息;
                :显示课程详情对话框;
            else (否)
                :显示课程不存在错误;
            endif
        elseif (导出课表?) then (是)
            :选择导出格式;
            :获取教师课表数据;
            :生成PDF/Excel文件;
            :触发文件下载;
        endif
    endwhile (否)
else (否)
    :重定向到登录页面;
    stop
endif

stop

@enduml 